version: "3.9"

services:
  backend:
    build:
      context: ./backend
      target: development
    volumes:
      - ./backend:/app
    environment:
      - MISTRAL_API_KEY=${MISTRAL_API_KEY}
      - STORAGE_PATH=/app/.data
    ports:
      - "8000:8000"
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

  frontend:
    build:
      context: ./frontend
      target: development
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_BACKEND_URL=${VITE_BACKEND_URL-http://localhost:8000}
    ports:
      - "5173:5173"
    command: ["npm", "run", "dev", "--", "--host", "0.0.0.0", "--port", "5173"]
    depends_on:
      - backend
