version: '3.9'

services:
  backend:
    build:
      context: ./backend
      target: dev
    environment:
      - MISTRAL_API_KEY=${MISTRAL_API_KEY:-}
      - MISTRAL_MODEL=${MISTRAL_MODEL:-mistral-large-latest}
      - MISTRAL_API_BASE=${MISTRAL_API_BASE:-https://api.mistral.ai/v1}
    ports:
      - '8000:8000'
    volumes:
      - ./backend:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build:
      context: ./frontend
      target: dev
    environment:
      - VITE_API_BASE_URL=http://localhost:8000
      - CHOKIDAR_USEPOLLING=1
    ports:
      - '5173:5173'
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
